// Generated by CoffeeScript 1.7.1
(function() {
  var newGame;

  newGame = function(W, H) {
    var game;
    game = {};
    game._element = document.getElementById('stage');
    game._element.style.width = W + 'px';
    game._element.style.height = H + 'px';
    game.canvas = document.createElement('canvas');
    game.ctx = game.canvas.getContext('2d');
    game.canvas.width = W;
    game.canvas.height = H;
    game.box = document.createElement('div');
    game.box.className = 'box';
    game.box.style.width = (W - 10) + 'px';
    game.box.style.minWidth = (W - 10) + 'px';
    game.box.style.maxWidth = (W - 10) + 'px';
    game._element.appendChild(game.canvas);
    game._element.appendChild(game.box);
    return game;
  };

  window.newGame = newGame;

}).call(this);
