// Generated by CoffeeScript 1.8.0
(function() {
  var main;

  main = function(game) {
    var idx, next, page;
    idx = 0;
    next = function() {
      ++idx;
      return page();
    };
    page = function() {
      var I, t;
      I = texts.length;
      idx = Math.max(idx, 0);
      idx = Math.min(idx, I - 1);
      t = texts[idx];
      if (t.image != null) {
        if (typeof console !== "undefined" && console !== null ? console.log : void 0) {
          console.log(t.image);
        }
        game.ctx.drawImage(t.image, 0, 0, W, H);
        game.box.style.display = 'none';
        next();
      } else if ((t.trim()) === '') {
        game.box.style.display = 'none';
      } else {
        game.box.innerHTML = t;
        game.box.style.color = random_color();
        game.box.style.display = 'block';
      }
      return idx + 1;
    };
    game.ctx.clearRect(0, 0, W, H);
    page();
    return game._element.addEventListener('click', function(e) {
      return next();
    });
  };

  window.main = main;

}).call(this);
