// Generated by CoffeeScript 1.8.0
(function() {
  var load;

  window.image_count = {
    loaded: 0,
    total: 0
  };

  load = function(type, src) {
    var img;
    img = new Image;
    window.image_count.total++;
    img.src = src;
    img.onload = function() {
      return window.image_count.loaded++;
    };
    return {
      image: img,
      type: type
    };
  };

  window.image = {
    background: function(src) {
      return load("background", src);
    }
  };

}).call(this);
