// Generated by CoffeeScript 1.8.0
(function() {
  window.image_count = {
    loaded: 0,
    total: 0
  };

  window.image = function(src) {
    var img;
    img = new Image;
    window.image_count.total++;
    img.src = src;
    img.onload = function() {
      return window.image_count.loaded++;
    };
    return {
      image: img
    };
  };

}).call(this);
