// Generated by CoffeeScript 1.8.0
(function() {
  var inc_load;

  window.image_count = {
    loaded: 0,
    total: 0
  };

  inc_load = function() {
    return ++window.image_count.loaded;
  };

  window.image = function(src) {
    var img;
    img = new Image;
    img.src = src;
    img.onload = inc_load;
    return {
      image: img
    };
  };

}).call(this);
