// Generated by CoffeeScript 1.7.1
(function() {
  window.set_size = function() {
    var H, W, i, _i;
    if (window.innerWidth) {
      W = window.innerWidth;
      H = window.innerHeight;
    } else if (document.body.clientWidth) {
      W = document.body.clientWidth;
      H = document.body.clientHeight;
    } else {
      W = 660;
      H = 500;
    }
    H = H - 20;
    W = W - 20;
    for (i = _i = 0; _i <= 10; i = ++_i) {
      H = Math.min(H, (W * 480 / 640) | 0);
      W = Math.min(W, (H * 640 / 480) | 0);
    }
    if ((typeof console !== "undefined" && console !== null ? console.log : void 0) != null) {
      console.log(W, H);
    }
    window.H = H;
    return window.W = W;
  };

}).call(this);
